-- TF2 Killstreak Weapon Sheen
-- Created by YuRaNnNzZZ

game.AddParticles( "particles/tf2_killstreaks.pcf" )
game.AddParticles( "particles/tf2_killstreaks_custom.pcf" )
PrecacheParticleSystem("killstreak_t1_lvl1")
PrecacheParticleSystem("killstreak_t1_lvl2")
PrecacheParticleSystem("killstreak_t2_lvl1")
PrecacheParticleSystem("killstreak_t2_lvl2")
PrecacheParticleSystem("killstreak_t3_lvl1")
PrecacheParticleSystem("killstreak_t3_lvl2")
PrecacheParticleSystem("killstreak_t4_lvl1")
PrecacheParticleSystem("killstreak_t4_lvl2")
PrecacheParticleSystem("killstreak_t5_lvl1")
PrecacheParticleSystem("killstreak_t5_lvl2")
PrecacheParticleSystem("killstreak_t6_lvl1")
PrecacheParticleSystem("killstreak_t6_lvl2")
PrecacheParticleSystem("killstreak_t7_lvl1")
PrecacheParticleSystem("killstreak_t7_lvl2")
PrecacheParticleSystem("killstreak_t8_lvl1")
PrecacheParticleSystem("killstreak_t8_lvl2")
PrecacheParticleSystem("killstreak_t9_lvl1")
PrecacheParticleSystem("killstreak_t9_lvl2")
PrecacheParticleSystem("killstreak_t10_lvl1")
PrecacheParticleSystem("killstreak_t10_lvl2")
PrecacheParticleSystem("killstreak_t11_lvl1")
PrecacheParticleSystem("killstreak_t11_lvl2")